Areas/Admin/Controllers/SliderController.cs
using EvaraMVC.DataContext;
using EvaraMVC.Modals;
using EvaraMVC.ViewModel.SliderVM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace EvaraMVC.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize]
public class SliderController : Controller
{
    readonly private EvaraDbContext _evaraDbContext;
    IWebHostEnvironment _environment;
    public SliderController(EvaraDbContext evaraDbContext, IWebHostEnvironment environment)
    {
        _environment = environment;
        _evaraDbContext = evaraDbContext;
    }
    public async Task<IActionResult> Index()
    {
        List<Slider> sliders = await _evaraDbContext.Sliders.ToListAsync();
        return View(sliders);
    }
    public async Task<IActionResult> Detalies(int id)
    {
        Slider? slider = await _evaraDbContext.Sliders.FindAsync(id);
        if (slider == null)
        {
            return NotFound();
        }
        return View(slider);
    }
    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(SliderCreateVM slider)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }
        if (slider.Image == null)
        {
            ModelState.AddModelError("Image", "Image is requared");
            return View(slider);
        }
        string guid = Guid.NewGuid().ToString();
        string newFilename = guid + slider.Image.FileName;
        string path = Path.Combine(_environment.WebRootPath, "assets", "imgs", "slider", newFilename);
        using (FileStream fileStream = new FileStream(path, FileMode.CreateNew))
        {
            await slider.Image.CopyToAsync(fileStream);
        }
        Slider newslider = new Slider()
        {
            Description = slider.Description,
            Title = slider.Title,
            ImageName = newFilename,
        };
        _evaraDbContext.Sliders.Add(newslider);
        await _evaraDbContext.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        Slider? slider = await _evaraDbContext.Sliders.FindAsync(id);
        if (slider == null)
        {
            return NotFound();
        }
        if (slider.ImageName != null)
        {
            string filepath = Path.Combine(_environment.WebRootPath, "assets", "imgs", "slider", slider.ImageName);
            if (System.IO.File.Exists(filepath))
            {
                System.IO.File.Delete(filepath);
            }
        }
        _evaraDbContext.Sliders.Remove(slider);
        await _evaraDbContext.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Edit(int id)
    {
        Slider? slider = await _evaraDbContext.Sliders.FindAsync(id);
        if (slider == null)
        {
            return NotFound();
        }
        SliderEditVM sliderVM = new SliderEditVM()
        {
            Description = slider.Description,
            ImageName = slider.ImageName,
            Title = slider.Title
        };
        return View(sliderVM);

    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, SliderEditVM sliderVM)
    {
        
        Slider? slider = await _evaraDbContext
            .Sliders
            .AsNoTracking()
            .Where(c => c.Id == id)
            .FirstOrDefaultAsync();
        if (slider == null) 
        { 
            return NotFound(); 
        }
        if (!ModelState.IsValid)
        {
            return View(slider);
        }
        if (sliderVM.Image is not  null)
        {
            string filepath = Path.Combine(_environment.WebRootPath, "assets", "imgs", "slider", slider.ImageName);
            if (System.IO.File.Exists(filepath))
            {
                System.IO.File.Delete(filepath);
            }

            string guid = Guid.NewGuid().ToString();
            string newFilename = guid + sliderVM.Image.FileName;
            string path = Path.Combine(_environment.WebRootPath, "assets", "imgs", "slider", newFilename);
            using (FileStream fileStream = new FileStream(path, FileMode.CreateNew))
            {
                await sliderVM.Image.CopyToAsync(fileStream);
            }
            sliderVM.ImageName = newFilename;
        }

        Slider NewDbSlide = new Slider()
        {
            Id = id,
            Title = sliderVM.Title,
            Description = sliderVM.Description,
            ImageName = sliderVM.ImageName,
        };

        _evaraDbContext.Sliders.Update(NewDbSlide);
        await _evaraDbContext.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
}

Areas/Admin/Views/Slider/Create.cshtml
@model SliderCreateVM
<h1>Slider create</h1>

<form class="col-6" method="post" enctype="multipart/form-data">
    <div class="form-group" >
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" id="exampleInputPassword1">
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" id="exampleInputPassword1">
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
    <div class="form-group">
        <label asp-for="Image"></label>
        <input asp-for="Image" class="form-control" id="exampleInputPassword1">
        <span class="text-danger" asp-validation-for="Image"></span>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form> 

Areas/Admin/Views/Slider/Detalies.cshtml
@model Slider
<h1>@Model.Title</h1>
<h1>@Model.Description</h1>
<h1>@Model.ImageName</h1>
<img style="width:400px" src="~/assets/imgs/slider/@Model.ImageName" />

Areas/Admin/Views/Slider/Edit.cshtml
@model SliderEditVM


<h1>Slider update</h1>


<form class="col-6" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" >
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" >
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>

    <div>
        <img style="width:400px" src="~/assets/imgs/slider/@Model.ImageName" />
        <input asp-for="ImageName" type="hidden">
    </div>

    <div class="form-group">
        <label asp-for="Image"></label>
        <input asp-for="Image" class="form-control">
        <span class="text-danger" asp-validation-for="Image"></span>
    </div>

    <button type="submit" class="btn btn-primary">Edit</button>
</form>

Areas/Admin/Views/Slider/Index.cshtml
@model List<Slider>
@{
    int count = 0;
}

<!-- Main Content -->
<div id="content">


    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Slider</h1>
        <p class="mb-4">
            DataTables is a third party plugin that is used to generate the demo table below.
            For more information about DataTables, please visit the <a target="_blank"
                                                                       href="https://datatables.net">official DataTables documentation</a>.
        </p>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card shadow mb-4">
                <div class="card-header py-3 d-flex justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
                    <div>
                        <a class="btn btn-success px-5" asp-action="Create">Create</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
            <table class="table table-bordered">

                <thead>
                    <tr>
                        <th>№</th>
                        <th>Title</th>
                        <th>Descriptio</th>
                        <th>Image</th>
                        <th>Setting</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Slider item in Model)
                    {
                        <tr>                                                                                                                                                                                                                                                                                              
                            <td>@(++count)</td>
                            <td>@item.Title</td>
                            <td>@item.Description</td>
                            <td><img style="width: 200px" src="~/assets/imgs/slider/@item.ImageName"></td>
                            <td>
                                <a asp-controller="Slider"  asp-action="Detalies" asp-route-Id="@item.Id"><button class="btn btn-info">Detail</button></a>
                                <a asp-controller="Slider" asp-action="Edit" asp-route-Id="@item.Id" class="btn btn-primary"> Update </a>
                                <form method="post" asp-action="Delete" asp-route-Id="@item.Id">
                                <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>

        </div>

    </div>
    <!-- /.container-fluid -->

</div>
<!-- End of Main Content -->