Areas/Admin/Controllers/SettingController.cs
using EvaraMVC.DataContext;
using EvaraMVC.Modals;
using EvaraMVC.ViewModel.SettingVM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EvaraMVC.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize]
public class SettingController : Controller
{
    readonly EvaraDbContext _context;
    public SettingController(EvaraDbContext context)
    { 
        _context = context;
    }

    public async Task<IActionResult> Index()
    {
        List<Setting> setting = await _context.Settings.ToListAsync(); 
        return View(setting);
    }
    public async Task<IActionResult> Edit(int id)
    {
        Setting? setting = await _context.Settings.FindAsync(id);
        if (setting == null)
        {
            return NotFound();
        }
        SettingEditVM editVM = new SettingEditVM()
        {
            Key = setting.Key,
            Value = setting.Value,
        };
        return View(editVM);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id ,SettingEditVM newSetting)
    {
        Setting? setting = await _context
            .Settings
            .Where(s => s.Id == id)
            .FirstOrDefaultAsync();
        if (setting == null)
        {
            return NotFound();
        }
        if (!ModelState.IsValid)
        {
            return View();
        }

        setting.Value = newSetting.Value;
        setting.Key = newSetting.Key;
        _context.Settings.Update(setting);
        _context.SaveChanges();
        return RedirectToAction(nameof(Index));
    }
}

Areas/Admin/Views/Setting/Edit.cshtml
@model SettingEditVM

<h1>Setting update</h1>


<form class="col-6" method="post">
    <div class="form-group">
        <label asp-for="Key"></label>
        <input asp-for="Key" class="form-control">
        <span class="text-danger" asp-validation-for="Key"></span>
    </div>

   

    <div class="form-group">
        <label asp-for="Value"></label>
        <input asp-for="Value" class="form-control">
        <span class="text-danger" asp-validation-for="Value"></span>
    </div>

    <button type="submit" class="btn btn-primary">Edit</button>
</form>

Areas/Admin/Views/Setting/Index.cshtml
@model List<Setting>
@{
    int count = 0;
}

<!-- Main Content -->
<div id="content">


    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Product</h1>
        <p class="mb-4">
            DataTables is a third party plugin that is used to generate the demo table below.
            For more information about DataTables, please visit the <a target="_blank"
                                                                       href="https://datatables.net">official DataTables documentation</a>.
        </p>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
                <div>
                    <a class="btn btn-success px-5" asp-action="Create">Create</a>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>№</th>
                                <th>Key</th>
                                <th>Value</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Setting item in Model)
                            {
                                <tr>
                                    <td>@(++count)</td>
                                    <td>@item.Key</td>
                                    <td>@item.Value</td>
                                    <td>
                                        <a asp-controller="Setting" asp-action="Edit" asp-route-Id="@item.Id" class="btn btn-primary"> Update </a>
                                        <form method="post" asp-action="Delete" asp-route-Id="@item.Id">
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->

</div>
<!-- End of Main Content -->