Areas/Admin/Controllers/CategoryController.cs
using EvaraMVC.DataContext;
using EvaraMVC.Modals;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;

namespace EvaraMVC.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize]
public class CategoryController : Controller
{
    readonly private EvaraDbContext _evaraDbContext;
    IWebHostEnvironment _environment;


    public CategoryController(EvaraDbContext evaraDbContext, IWebHostEnvironment environment)
    {
        _environment = environment;
        _evaraDbContext = evaraDbContext;
    }

    public async Task<IActionResult> Index()
    {
        List<Category> categories = await _evaraDbContext.Categories.ToListAsync();
        return View(categories);
    }

    public async Task<IActionResult> Detalies(int id)
    {
        Category? category = await _evaraDbContext.Categories.FindAsync(id);
        if (category == null)
        {
            return NotFound();
        }
        return View(category);
    }

    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Category category)
    {
        if (!ModelState.IsValid)
        {
            return View(category);
        }
        if (category.Image == null)
        {
            ModelState.AddModelError("Image", "Image is requared");
            return View(category);
        }

        string guid = Guid.NewGuid().ToString();
        string newFilename = guid + category.Image.FileName;
        string path = Path.Combine(_environment.WebRootPath, "assets", "imgs", "shop", newFilename);
        using (FileStream fileStream = new FileStream(path, FileMode.CreateNew))
        {
            await category.Image.CopyToAsync(fileStream);
        }

        category.ImageName = newFilename;
        _evaraDbContext.Categories.Add(category);
        await _evaraDbContext.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        Category? category = await _evaraDbContext.Categories.FindAsync(id);
        if (category == null)
        {
            return NotFound();
        }
        if (category.ImageName != null)
        {
            string filepath = Path.Combine(_environment.WebRootPath, "assets", "imgs", "shop", category.ImageName);
            if (System.IO.File.Exists(filepath))
            {
                System.IO.File.Delete(filepath);
            }
        }
        _evaraDbContext.Categories.Remove(category);
        await _evaraDbContext.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Edit(int id)
    {
        Category? category = await _evaraDbContext.Categories.FindAsync(id);
        if (category == null)
        {
            return NotFound();
        }
        return View(category);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Category newcatagory)
    {

        Category? category = await _evaraDbContext
            .Categories
            .AsNoTracking()
            .Where(c => c.Id == newcatagory.Id)
            .FirstOrDefaultAsync();
        if (category == null)
        {
            return NotFound();
        }

        if (!ModelState.IsValid)
        {
            return View(category);
        }


        if (newcatagory.Image is not null)
        {
            string filepath = Path.Combine(_environment.WebRootPath, "assets", "imgs", "shop", category.ImageName);
            if (System.IO.File.Exists(filepath))
            {
                System.IO.File.Delete(filepath);
            }

            string guid = Guid.NewGuid().ToString();
            string newFilename = guid + newcatagory.Image.FileName;
            string path = Path.Combine(_environment.WebRootPath, "assets", "imgs", "shop", newFilename);
            using (FileStream fileStream = new FileStream(path, FileMode.CreateNew))
            {
                await newcatagory.Image.CopyToAsync(fileStream);
            }
            newcatagory.ImageName = newFilename;


        }

        _evaraDbContext.Categories.Update(newcatagory);



        await _evaraDbContext.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }




    //public async Task<IActionResult> Index()
    //{
    //    List<Category> categories = await _evaraDbContext.Categories.ToListAsync();
    //    return View(categories);
    //}

    //public async Task<IActionResult> Detalies(int id)
    //{
    //    Category? category = await _evaraDbContext.Categories.FindAsync(id);
    //    if (category == null)
    //    {
    //        return NotFound();
    //    }
    //    return View(category);
    //}
    //public IActionResult Create()
    //{
    //    return View();
    //}
    //[HttpPost]
    //[ValidateAntiForgeryToken]
    //public async Task<IActionResult> Create(Category category)
    //{
    //    if (!ModelState.IsValid)
    //    {
    //        return View();
    //    }
    //    if (_evaraDbContext.Categories.Any(c => c.Name.Trim().ToLower() == category.Name.Trim().ToLower()))
    //    {
    //        ModelState.AddModelError("Name", "Bu adda category var");
    //        return View();
    //    }
    //    await _evaraDbContext.Categories.AddAsync(category);
    //    await _evaraDbContext.SaveChangesAsync();
    //    return RedirectToAction(nameof(Index));
    //}
    //[HttpPost]
    //[ValidateAntiForgeryToken]
    //public async Task<IActionResult> Delete(int id)
    //{
    //    Category? category = await _evaraDbContext.Categories.FindAsync(id);
    //    if (category == null)
    //    {
    //        return NotFound();
    //    }
    //    _evaraDbContext.Categories.Remove(category);
    //    await _evaraDbContext.SaveChangesAsync();
    //    return RedirectToAction(nameof(Index));
    //}

    //public IActionResult UpdateCategory()
    //{
    //    return View();
    //}

    //[HttpPost]
    //public async Task<IActionResult> UpdateCategory(Category newcategory)
    //{
    //    Category? category = _evaraDbContext.Categories.Find(newcategory.Id);

    //    if (!ModelState.IsValid)
    //    {
    //        return View();
    //    }

    //    if (_evaraDbContext.Categories.Any(c => c.Name.Trim().ToLower() == newcategory.Name.Trim().ToLower()))
    //    {
    //        ModelState.AddModelError("Name", "Bu adda category var");
    //        return View();
    //    }

    //    category.Name = newcategory.Name;


    //    _evaraDbContext.Categories.Update(category);
    //    await _evaraDbContext.SaveChangesAsync();
    //    return RedirectToAction(nameof(Index));

    //}




}

Areas/Admin/Views/Category/Create.cshtml
@model Category
<h1>Category create</h1>

<form class="col-6" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" id="exampleInputPassword1">
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Image"></label>
        <input asp-for="Image" class="form-control" id="exampleInputPassword1">
        <span class="text-danger" asp-validation-for="Image"></span>
    </div>
    <button type="submit" class="btn btn-primary" >Create</button>
</form> 

Areas/Admin/Views/Category/Detalies.cshtml
@model Category

<h1>@Model.Id</h1>
<h1>@Model.Name</h1>
<h1>@Model.ImageName</h1>
<img style="width:400px" src="~/assets/imgs/shop/@Model.ImageName" />

Areas/Admin/Views/Category/Edit.cshtml
@model Category

<h1>Catagory update</h1>


<form class="col-6" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control">
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>

    <div>
        <img style="width:400px" src="~/assets/imgs/shop/@Model.ImageName" />
        <input asp-for="ImageName" type="hidden">
    </div>

    <div class="form-group">
        <label asp-for="Image"></label>
        <input asp-for="Image" class="form-control">
        <span class="text-danger" asp-validation-for="Image"></span>
    </div>

    <button type="submit" class="btn btn-primary">Edit</button>
</form>

Areas/Admin/Views/Category/Index.cshtml
@model List<Category>
@{
    int count = 0;
}

<!-- Main Content -->
<div id="content">


    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Category</h1>
        <p class="mb-4">
            DataTables is a third party plugin that is used to generate the demo table below.
            For more information about DataTables, please visit the <a target="_blank"
                                                                       href="https://datatables.net">official DataTables documentation</a>.
        </p>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
                <div>
                    <a class="btn btn-success px-5" asp-action="Create">Create</a>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>№</th>
                                <th>Name</th>
                                <th>Setting</th>
                                <th>Image</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Category item in Model)
                            {
                                <tr>
                                    <td>@(++count)</td>
                                    <td>@item.Name</td>
                                    <td><img style="width: 200px" src="~/assets/imgs/shop/@item.ImageName"></td>
                                    <td>
                                        <a asp-controller="Category" asp-action="Detalies" asp-route-Id="@item.Id"><button class="btn btn-info">Detail</button></a>
                                        <a asp-controller="Category" asp-action="Edit" asp-route-Id="@item.Id" class="btn btn-primary"> Update </a>
                                        <form method="post" asp-action="Delete" asp-route-Id="@item.Id">
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->

</div>
<!-- End of Main Content -->