Areas/Admin/Controllers/PopularController.cs
using EvaraMVC.DataContext;
using EvaraMVC.Modals;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EvaraMVC.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize]
public class PopularController : Controller
{
    readonly private EvaraDbContext _evaraDbContext;
    IWebHostEnvironment _environment;
    public PopularController(EvaraDbContext evaraDbContext, IWebHostEnvironment environment)
    {
        _environment = environment;
        _evaraDbContext = evaraDbContext;
    }
    public async Task<IActionResult> Index()
    {
        List<Popular> populars = await _evaraDbContext.Populars.ToListAsync();
        return View(populars);
    }
    public async Task<IActionResult> Detalies(int id)
    {
        Popular? popular = await _evaraDbContext.Populars.FindAsync(id);
        if (popular == null)
        {
            return NotFound();
        }
        return View(popular);
    }
    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Popular popular)
    {
        if (!ModelState.IsValid)
        {
            return View(popular);
        }
        if (popular.Image == null)
        {
            ModelState.AddModelError("Image", "Image is requared");
            return View(popular);
        }

        string guid = Guid.NewGuid().ToString();
        string newFilename = guid + popular.Image.FileName;
        string path = Path.Combine(_environment.WebRootPath, "assets", "imgs", "banner", newFilename);
        using (FileStream fileStream = new FileStream(path, FileMode.CreateNew))
        {
            await popular.Image.CopyToAsync(fileStream);
        }

        popular.ImageName = newFilename;
        _evaraDbContext.Populars.Add(popular);
        await _evaraDbContext.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        Popular? popular = await _evaraDbContext.Populars.FindAsync(id);
        if (popular == null)
        {
            return NotFound();
        }
        if (popular.ImageName != null)
        {
            string filepath = Path.Combine(_environment.WebRootPath, "assets", "imgs", "banner", popular.ImageName);
            if (System.IO.File.Exists(filepath))
            {
                System.IO.File.Delete(filepath);
            }
        }
        _evaraDbContext.Populars.Remove(popular);
        await _evaraDbContext.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Edit(int id)
    {
        Popular? popular = await _evaraDbContext.Populars.FindAsync(id);
        if (popular == null)
        {
            return NotFound();
        }
        return View(popular);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, Popular newpopular)
    {

        Popular? popular = await _evaraDbContext
            .Populars
            .AsNoTracking()
            .Where(c => c.Id == id)
            .FirstOrDefaultAsync();
        if (popular == null)
        {
            return NotFound();
        }

        if (!ModelState.IsValid)
        {
            return View(popular);
        }
        if (newpopular.Image is not null)
        {
            string filepath = Path.Combine(_environment.WebRootPath, "assets", "imgs", "banner", popular.ImageName);
            if (System.IO.File.Exists(filepath))
            {
                System.IO.File.Delete(filepath);
            }
            string guid = Guid.NewGuid().ToString();
            string newFilename = guid + newpopular.Image.FileName;
            string path = Path.Combine(_environment.WebRootPath, "assets", "imgs", "banner", newFilename);
            using (FileStream fileStream = new FileStream(path, FileMode.CreateNew))
            {
                await newpopular.Image.CopyToAsync(fileStream);
            }
            newpopular.ImageName = newFilename;
        }
        _evaraDbContext.Populars.Update(newpopular);
        await _evaraDbContext.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }


}

Areas/Admin/Views/Popular/Create.cshtml
@model Popular
<h1>Popular create</h1>

<form class="col-6" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" id="exampleInputPassword1">
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>
    <div class="form-group">
        <label asp-for="Image"></label>
        <input asp-for="Image" class="form-control" id="exampleInputPassword1">
        <span class="text-danger" asp-validation-for="Image"></span>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

Areas/Admin/Views/Popular/Detalies.cshtml
@model Popular

<h1>@Model.Id</h1>
<h1>@Model.Title</h1>
<h1>@Model.ImageName</h1>
<img style="width:400px" src="~/assets/imgs/banner/@Model.ImageName" />

Areas/Admin/Views/Popular/Edit.cshtml
@model Popular

<h1>Popular update</h1>


<form class="col-6" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control">
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>

    <div>
        <img style="width:400px" src="~/assets/imgs/banner/@Model.ImageName" />
        <input asp-for="ImageName" type="hidden">
    </div>
    
    <div class="form-group">
        <label asp-for="Image"></label>
        <input asp-for="Image" class="form-control">
        <span class="text-danger" asp-validation-for="Image"></span>
    </div>

    <button type="submit" class="btn btn-primary">Edit</button>
</form>

Areas/Admin/Views/Popular/Index.cshtml
@model List<Popular>
@{
    int count = 0;
}

<!-- Main Content -->
<div id="content">


    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Popular</h1>
        <p class="mb-4">
            DataTables is a third party plugin that is used to generate the demo table below.
            For more information about DataTables, please visit the <a target="_blank"
                                                                       href="https://datatables.net">official DataTables documentation</a>.
        </p>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card shadow mb-4">
                <div class="card-header py-3 d-flex justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
                    <div>
                        <a class="btn btn-success px-5" asp-action="Create">Create</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered">

                            <thead>
                                <tr>
                                    <th>№</th>
                                    <th>Title</th>
                                    <th>Image</th>
                                    <th>Setting</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (Popular item in Model)
                                {
                                    <tr>
                                        <td>@(++count)</td>
                                        <td>@item.Title</td>
                                        <td><img style="width: 200px" src="~/assets/imgs/banner/@item.ImageName"></td>
                                        <td>
                                            <a asp-controller="Popular" asp-action="Detalies" asp-route-Id="@item.Id"><button class="btn btn-info">Detail</button></a>
                                            <a asp-controller="Popular" asp-action="Edit" asp-route-Id="@item.Id" class="btn btn-primary"> Update </a>
                                            <form method="post" asp-action="Delete" asp-route-Id="@item.Id">
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>

                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->